table Anagrafica_Clienti_c_f
	lineageTag: 37ac2a2d-a61a-4609-a6a5-b7f53e81875d

	column 'Codice Cliente'
		dataType: int64
		formatString: 0
		lineageTag: 0749b280-ceca-4691-b1a7-71f3013649e2
		summarizeBy: none
		sourceColumn: Codice Cliente

		annotation SummarizationSetBy = Automatic

	column 'Codice Gruppo Merceologico'
		dataType: string
		lineageTag: 327bc6d4-8d7b-4328-bf1f-2a9bbe83f4b7
		summarizeBy: none
		sourceColumn: Codice Gruppo Merceologico

		annotation SummarizationSetBy = Automatic

	partition Anagrafica_Clienti_c_f = m
		mode: import
		source =
				let
				    Origine = Odbc.Query("dsn=F12 Informix DB", "SELECT * FROM c_f"),
				    #"Rimosse altre colonne" = Table.SelectColumns(Origine,{"cf_cod_s_conto", "cf_gruppo_merc"}),
				    #"Rinominate colonne" = Table.RenameColumns(#"Rimosse altre colonne",{{"cf_cod_s_conto", "Codice Cliente"}, {"cf_gruppo_merc", "Codice Gruppo Merceologico"}})
				in
				    #"Rinominate colonne"

	annotation PBI_NavigationStepName = Navigazione

	annotation PBI_ResultType = Table

